/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemMonitor */

#ifndef _Included_SystemMonitor
#define _Included_SystemMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemMonitor
 * Method:    getMemoryLoad
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_SystemMonitor_getMemoryLoad
  (JNIEnv *, jobject);

/*
 * Class:     SystemMonitor
 * Method:    getProcessList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SystemMonitor_getProcessList
  (JNIEnv *, jobject);

/*
 * Class:     SystemMonitor
 * Method:    killProcess
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_SystemMonitor_killProcess
  (JNIEnv *, jobject, jint);

/*
 * Class:     SystemMonitor
 * Method:    getCpuLoad
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_SystemMonitor_getCpuLoad
  (JNIEnv *, jobject);

/*
 * Class:     SystemMonitor
 * Method:    getGpuData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SystemMonitor_getGpuData
  (JNIEnv *, jobject);

/*
 * Class:     SystemMonitor
 * Method:    getDiskData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SystemMonitor_getDiskData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
